[2024-10-09T01:38:23.382+0000] {processor.py:161} INFO - Started process (PID=3275) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:38:23.383+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T01:38:23.386+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:38:23.385+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:38:23.402+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:38:23.398+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.datasets import load_iris
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T01:38:23.402+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:38:23.424+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.049 seconds
[2024-10-09T01:38:53.851+0000] {processor.py:161} INFO - Started process (PID=3334) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:38:53.853+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T01:38:53.856+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:38:53.855+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:38:53.863+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:38:53.861+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.datasets import load_iris
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T01:38:53.863+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:38:53.882+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.041 seconds
[2024-10-09T01:39:24.431+0000] {processor.py:161} INFO - Started process (PID=3392) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:39:24.434+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T01:39:24.439+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:39:24.438+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:39:24.449+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:39:24.447+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.datasets import load_iris
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T01:39:24.449+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:39:24.471+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.053 seconds
[2024-10-09T01:39:54.990+0000] {processor.py:161} INFO - Started process (PID=3451) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:39:54.994+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T01:39:55.000+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:39:54.999+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:39:55.013+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:39:55.009+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.datasets import load_iris
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T01:39:55.013+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:39:55.040+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.065 seconds
[2024-10-09T01:40:25.489+0000] {processor.py:161} INFO - Started process (PID=3510) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:40:25.492+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T01:40:25.495+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:40:25.495+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:40:25.504+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:40:25.502+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.datasets import load_iris
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T01:40:25.505+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:40:25.523+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.044 seconds
[2024-10-09T01:40:56.165+0000] {processor.py:161} INFO - Started process (PID=3569) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:40:56.168+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T01:40:56.172+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:40:56.172+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:40:56.189+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:40:56.184+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.datasets import load_iris
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T01:40:56.190+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:40:56.217+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.064 seconds
[2024-10-09T01:41:26.649+0000] {processor.py:161} INFO - Started process (PID=3628) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:41:26.654+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T01:41:26.662+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:41:26.661+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:41:26.672+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:41:26.670+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.datasets import load_iris
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T01:41:26.674+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:41:26.706+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.076 seconds
[2024-10-09T01:41:57.153+0000] {processor.py:161} INFO - Started process (PID=3687) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:41:57.157+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T01:41:57.162+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:41:57.161+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:41:57.171+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:41:57.169+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.datasets import load_iris
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T01:41:57.172+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:41:57.193+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.052 seconds
[2024-10-09T01:41:58.185+0000] {processor.py:161} INFO - Started process (PID=3688) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:41:58.187+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T01:41:58.190+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:41:58.190+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:41:58.203+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:41:58.202+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.datasets import load_iris
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T01:41:58.204+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:41:58.221+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.045 seconds
[2024-10-09T01:42:28.365+0000] {processor.py:161} INFO - Started process (PID=3747) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:42:28.369+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T01:42:28.374+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:42:28.373+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:42:28.383+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:42:28.381+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.datasets import load_iris
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T01:42:28.383+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:42:28.421+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.073 seconds
[2024-10-09T01:42:58.682+0000] {processor.py:161} INFO - Started process (PID=3806) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:42:58.686+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T01:42:58.690+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:42:58.689+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:42:58.704+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:42:58.702+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.datasets import load_iris
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T01:42:58.704+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:42:58.726+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.060 seconds
[2024-10-09T01:43:28.838+0000] {processor.py:161} INFO - Started process (PID=3865) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:43:28.840+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T01:43:28.842+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:43:28.842+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:43:28.847+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:43:28.846+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.datasets import load_iris
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T01:43:28.847+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:43:28.862+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.029 seconds
[2024-10-09T01:43:59.217+0000] {processor.py:161} INFO - Started process (PID=3924) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:43:59.220+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T01:43:59.224+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:43:59.223+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:43:59.232+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:43:59.230+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.datasets import load_iris
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T01:43:59.233+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:43:59.253+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.047 seconds
[2024-10-09T01:44:29.461+0000] {processor.py:161} INFO - Started process (PID=3983) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:44:29.464+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T01:44:29.468+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:44:29.468+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:44:29.476+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:44:29.475+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.datasets import load_iris
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T01:44:29.477+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:44:29.499+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.055 seconds
[2024-10-09T01:44:59.597+0000] {processor.py:161} INFO - Started process (PID=4042) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:44:59.600+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T01:44:59.606+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:44:59.605+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:44:59.614+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:44:59.612+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.datasets import load_iris
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T01:44:59.615+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:44:59.654+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.071 seconds
[2024-10-09T01:45:27.637+0000] {processor.py:161} INFO - Started process (PID=4102) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:45:27.644+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T01:45:27.658+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:45:27.655+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:45:27.671+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:45:27.670+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.datasets import load_iris
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T01:45:27.672+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:45:27.696+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.070 seconds
[2024-10-09T01:45:57.817+0000] {processor.py:161} INFO - Started process (PID=4161) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:45:57.820+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T01:45:57.824+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:45:57.824+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:45:57.832+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:45:57.831+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.datasets import load_iris
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T01:45:57.833+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:45:57.856+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.053 seconds
[2024-10-09T01:46:28.387+0000] {processor.py:161} INFO - Started process (PID=4220) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:46:28.391+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T01:46:28.394+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:46:28.393+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:46:28.403+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:46:28.401+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.datasets import load_iris
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T01:46:28.404+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:46:28.422+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.045 seconds
[2024-10-09T01:46:52.692+0000] {processor.py:161} INFO - Started process (PID=4271) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:46:52.694+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T01:46:52.696+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:46:52.696+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:46:52.708+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:46:52.706+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T01:46:52.709+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:46:52.726+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.040 seconds
[2024-10-09T01:47:23.409+0000] {processor.py:161} INFO - Started process (PID=4330) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:47:23.411+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T01:47:23.419+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:47:23.418+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:47:23.444+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:47:23.435+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T01:47:23.445+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:47:23.481+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.081 seconds
[2024-10-09T01:47:54.197+0000] {processor.py:161} INFO - Started process (PID=4389) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:47:54.200+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T01:47:54.205+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:47:54.204+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:47:54.214+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:47:54.212+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T01:47:54.214+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:47:54.244+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.057 seconds
[2024-10-09T01:48:24.898+0000] {processor.py:161} INFO - Started process (PID=4448) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:48:24.901+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T01:48:24.904+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:48:24.904+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:48:24.913+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:48:24.910+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T01:48:24.914+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:48:24.931+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.042 seconds
[2024-10-09T01:48:55.557+0000] {processor.py:161} INFO - Started process (PID=4513) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:48:55.559+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T01:48:55.561+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:48:55.561+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:48:55.567+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:48:55.566+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T01:48:55.568+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:48:55.583+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.033 seconds
[2024-10-09T01:49:25.956+0000] {processor.py:161} INFO - Started process (PID=4572) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:49:25.958+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T01:49:25.962+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:49:25.961+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:49:25.969+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:49:25.968+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T01:49:25.971+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:49:26.028+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.082 seconds
[2024-10-09T01:49:56.300+0000] {processor.py:161} INFO - Started process (PID=4631) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:49:56.302+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T01:49:56.306+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:49:56.305+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:49:56.315+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:49:56.312+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T01:49:56.316+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:49:56.337+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.047 seconds
[2024-10-09T01:50:26.678+0000] {processor.py:161} INFO - Started process (PID=4690) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:50:26.680+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T01:50:26.683+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:50:26.682+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:50:26.692+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:50:26.690+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T01:50:26.693+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:50:26.714+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.046 seconds
[2024-10-09T01:50:56.992+0000] {processor.py:161} INFO - Started process (PID=4748) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:50:56.995+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T01:50:56.998+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:50:56.998+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:50:57.006+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:50:57.004+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T01:50:57.007+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:50:57.026+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.044 seconds
[2024-10-09T01:51:27.506+0000] {processor.py:161} INFO - Started process (PID=4807) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:51:27.509+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T01:51:27.513+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:51:27.512+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:51:27.522+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:51:27.520+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T01:51:27.523+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:51:27.542+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.044 seconds
[2024-10-09T01:51:57.790+0000] {processor.py:161} INFO - Started process (PID=4866) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:51:57.793+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T01:51:57.796+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:51:57.796+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:51:57.806+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:51:57.804+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T01:51:57.807+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:51:57.826+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.045 seconds
[2024-10-09T01:52:28.188+0000] {processor.py:161} INFO - Started process (PID=4925) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:52:28.190+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T01:52:28.194+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:52:28.194+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:52:28.202+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:52:28.200+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T01:52:28.203+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:52:28.221+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.041 seconds
[2024-10-09T01:52:58.335+0000] {processor.py:161} INFO - Started process (PID=4984) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:52:58.338+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T01:52:58.341+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:52:58.341+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:52:58.350+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:52:58.348+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T01:52:58.352+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:52:58.371+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.048 seconds
[2024-10-09T01:53:29.018+0000] {processor.py:161} INFO - Started process (PID=5044) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:53:29.021+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T01:53:29.024+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:53:29.024+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:53:29.033+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:53:29.031+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T01:53:29.034+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:53:29.054+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.045 seconds
[2024-10-09T01:53:59.293+0000] {processor.py:161} INFO - Started process (PID=5103) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:53:59.296+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T01:53:59.300+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:53:59.299+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:53:59.309+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:53:59.307+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T01:53:59.310+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:53:59.330+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.046 seconds
[2024-10-09T01:54:29.634+0000] {processor.py:161} INFO - Started process (PID=5163) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:54:29.636+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T01:54:29.640+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:54:29.639+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:54:29.647+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:54:29.645+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T01:54:29.648+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:54:29.666+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.040 seconds
[2024-10-09T01:54:59.958+0000] {processor.py:161} INFO - Started process (PID=5221) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:54:59.960+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T01:54:59.965+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:54:59.964+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:54:59.973+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:54:59.971+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T01:54:59.973+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:54:59.994+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.047 seconds
[2024-10-09T01:55:30.170+0000] {processor.py:161} INFO - Started process (PID=5280) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:55:30.172+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T01:55:30.175+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:55:30.174+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:55:30.182+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:55:30.181+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T01:55:30.183+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:55:30.202+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.043 seconds
[2024-10-09T01:56:00.855+0000] {processor.py:161} INFO - Started process (PID=5340) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:56:00.859+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T01:56:00.864+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:56:00.863+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:56:00.873+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:56:00.871+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T01:56:00.875+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:56:00.897+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.055 seconds
[2024-10-09T01:56:31.421+0000] {processor.py:161} INFO - Started process (PID=5399) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:56:31.423+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T01:56:31.427+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:56:31.426+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:56:31.434+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:56:31.433+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T01:56:31.435+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:56:31.456+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.043 seconds
[2024-10-09T01:57:02.418+0000] {processor.py:161} INFO - Started process (PID=5459) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:57:02.421+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T01:57:02.426+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:57:02.425+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:57:02.434+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:57:02.432+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T01:57:02.435+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:57:02.456+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.050 seconds
[2024-10-09T01:57:32.837+0000] {processor.py:161} INFO - Started process (PID=5518) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:57:32.840+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T01:57:32.842+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:57:32.842+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:57:32.851+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:57:32.849+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T01:57:32.852+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:57:32.869+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.041 seconds
[2024-10-09T01:58:03.469+0000] {processor.py:161} INFO - Started process (PID=5577) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:58:03.472+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T01:58:03.475+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:58:03.474+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:58:03.484+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:58:03.482+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T01:58:03.485+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:58:03.503+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.043 seconds
[2024-10-09T01:58:34.228+0000] {processor.py:161} INFO - Started process (PID=5635) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:58:34.230+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T01:58:34.233+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:58:34.233+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:58:34.241+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:58:34.239+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T01:58:34.241+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:58:34.261+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.041 seconds
[2024-10-09T01:59:04.447+0000] {processor.py:161} INFO - Started process (PID=5694) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:59:04.450+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T01:59:04.454+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:59:04.453+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:59:04.463+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:59:04.461+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T01:59:04.464+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:59:04.482+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.045 seconds
[2024-10-09T01:59:34.844+0000] {processor.py:161} INFO - Started process (PID=5753) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:59:34.847+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T01:59:34.850+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:59:34.849+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:59:34.857+0000] {logging_mixin.py:188} INFO - [2024-10-09T01:59:34.855+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T01:59:34.858+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T01:59:34.879+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.043 seconds
[2024-10-09T02:00:05.119+0000] {processor.py:161} INFO - Started process (PID=5812) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:00:05.121+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T02:00:05.124+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:00:05.124+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:00:05.140+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:00:05.138+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T02:00:05.141+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:00:05.158+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.045 seconds
[2024-10-09T02:00:35.407+0000] {processor.py:161} INFO - Started process (PID=5870) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:00:35.409+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T02:00:35.411+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:00:35.411+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:00:35.418+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:00:35.417+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T02:00:35.420+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:00:35.437+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.037 seconds
[2024-10-09T02:01:05.676+0000] {processor.py:161} INFO - Started process (PID=5928) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:01:05.678+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T02:01:05.681+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:01:05.680+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:01:05.687+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:01:05.686+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T02:01:05.689+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:01:05.705+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.037 seconds
[2024-10-09T02:01:36.620+0000] {processor.py:161} INFO - Started process (PID=5988) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:01:36.623+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T02:01:36.627+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:01:36.626+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:01:36.636+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:01:36.634+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T02:01:36.637+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:01:36.656+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.044 seconds
[2024-10-09T02:02:07.332+0000] {processor.py:161} INFO - Started process (PID=6047) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:02:07.335+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T02:02:07.339+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:02:07.338+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:02:07.348+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:02:07.346+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T02:02:07.354+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:02:07.375+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.051 seconds
[2024-10-09T02:02:38.273+0000] {processor.py:161} INFO - Started process (PID=6106) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:02:38.276+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T02:02:38.279+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:02:38.279+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:02:38.288+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:02:38.286+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T02:02:38.289+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:02:38.308+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.043 seconds
[2024-10-09T02:03:08.900+0000] {processor.py:161} INFO - Started process (PID=6165) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:03:08.902+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T02:03:08.905+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:03:08.905+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:03:08.915+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:03:08.913+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T02:03:08.915+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:03:08.934+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.043 seconds
[2024-10-09T02:03:39.840+0000] {processor.py:161} INFO - Started process (PID=6224) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:03:39.842+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T02:03:39.845+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:03:39.845+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:03:39.854+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:03:39.852+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T02:03:39.856+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:03:39.874+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.043 seconds
[2024-10-09T02:04:10.624+0000] {processor.py:161} INFO - Started process (PID=6283) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:04:10.628+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T02:04:10.632+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:04:10.631+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:04:10.640+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:04:10.638+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T02:04:10.641+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:04:10.661+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.049 seconds
[2024-10-09T02:04:40.966+0000] {processor.py:161} INFO - Started process (PID=6342) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:04:40.969+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T02:04:40.973+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:04:40.972+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:04:40.981+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:04:40.979+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 4, in <module>
    from sklearn.model_selection import train_test_split
ModuleNotFoundError: No module named 'sklearn'
[2024-10-09T02:04:40.982+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:04:41.003+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 0.046 seconds
[2024-10-09T02:06:01.906+0000] {processor.py:161} INFO - Started process (PID=59) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:06:01.912+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T02:06:01.916+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:06:01.915+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:06:04.067+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:06:04.067+0000] {font_manager.py:1584} INFO - generated new fontManager
[2024-10-09T02:06:04.382+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:06:04.379+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 14, in <module>
    from keras.models import Sequential
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/__init__.py", line 4, in <module>
    from keras.api import DTypePolicy
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/api/__init__.py", line 8, in <module>
    from keras.api import activations
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/api/activations/__init__.py", line 7, in <module>
    from keras.src.activations import deserialize
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/__init__.py", line 1, in <module>
    from keras.src import activations
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/activations/__init__.py", line 3, in <module>
    from keras.src.activations.activations import elu
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/activations/activations.py", line 1, in <module>
    from keras.src import backend
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/backend/__init__.py", line 9, in <module>
    from keras.src.backend.common.dtypes import result_type
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/backend/common/__init__.py", line 2, in <module>
    from keras.src.backend.common.dtypes import result_type
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/backend/common/dtypes.py", line 5, in <module>
    from keras.src.backend.common.variables import standardize_dtype
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/backend/common/variables.py", line 11, in <module>
    from keras.src.utils.module_utils import tensorflow as tf
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/utils/__init__.py", line 1, in <module>
    from keras.src.utils.audio_dataset_utils import audio_dataset_from_directory
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/utils/audio_dataset_utils.py", line 4, in <module>
    from keras.src.utils import dataset_utils
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/utils/dataset_utils.py", line 9, in <module>
    from keras.src import tree
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/tree/__init__.py", line 1, in <module>
    from keras.src.tree.tree_api import assert_same_structure
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/tree/tree_api.py", line 6, in <module>
    from keras.src.tree import optree_impl as tree_impl
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/tree/optree_impl.py", line 17, in <module>
    from tensorflow.python.trackable.data_structures import ListWrapper
ModuleNotFoundError: No module named 'tensorflow'
[2024-10-09T02:06:04.383+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:06:04.407+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 2.511 seconds
[2024-10-09T02:06:34.997+0000] {processor.py:161} INFO - Started process (PID=134) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:06:34.999+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T02:06:35.002+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:06:35.002+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:06:36.190+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:06:36.186+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 14, in <module>
    from keras.models import Sequential
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/__init__.py", line 4, in <module>
    from keras.api import DTypePolicy
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/api/__init__.py", line 8, in <module>
    from keras.api import activations
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/api/activations/__init__.py", line 7, in <module>
    from keras.src.activations import deserialize
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/__init__.py", line 1, in <module>
    from keras.src import activations
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/activations/__init__.py", line 3, in <module>
    from keras.src.activations.activations import elu
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/activations/activations.py", line 1, in <module>
    from keras.src import backend
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/backend/__init__.py", line 9, in <module>
    from keras.src.backend.common.dtypes import result_type
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/backend/common/__init__.py", line 2, in <module>
    from keras.src.backend.common.dtypes import result_type
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/backend/common/dtypes.py", line 5, in <module>
    from keras.src.backend.common.variables import standardize_dtype
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/backend/common/variables.py", line 11, in <module>
    from keras.src.utils.module_utils import tensorflow as tf
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/utils/__init__.py", line 1, in <module>
    from keras.src.utils.audio_dataset_utils import audio_dataset_from_directory
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/utils/audio_dataset_utils.py", line 4, in <module>
    from keras.src.utils import dataset_utils
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/utils/dataset_utils.py", line 9, in <module>
    from keras.src import tree
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/tree/__init__.py", line 1, in <module>
    from keras.src.tree.tree_api import assert_same_structure
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/tree/tree_api.py", line 6, in <module>
    from keras.src.tree import optree_impl as tree_impl
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/tree/optree_impl.py", line 17, in <module>
    from tensorflow.python.trackable.data_structures import ListWrapper
ModuleNotFoundError: No module named 'tensorflow'
[2024-10-09T02:06:36.191+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:06:36.203+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 1.215 seconds
[2024-10-09T02:07:06.721+0000] {processor.py:161} INFO - Started process (PID=204) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:07:06.724+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T02:07:06.727+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:07:06.726+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:07:07.840+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:07:07.837+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 14, in <module>
    from keras.models import Sequential
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/__init__.py", line 4, in <module>
    from keras.api import DTypePolicy
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/api/__init__.py", line 8, in <module>
    from keras.api import activations
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/api/activations/__init__.py", line 7, in <module>
    from keras.src.activations import deserialize
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/__init__.py", line 1, in <module>
    from keras.src import activations
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/activations/__init__.py", line 3, in <module>
    from keras.src.activations.activations import elu
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/activations/activations.py", line 1, in <module>
    from keras.src import backend
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/backend/__init__.py", line 9, in <module>
    from keras.src.backend.common.dtypes import result_type
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/backend/common/__init__.py", line 2, in <module>
    from keras.src.backend.common.dtypes import result_type
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/backend/common/dtypes.py", line 5, in <module>
    from keras.src.backend.common.variables import standardize_dtype
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/backend/common/variables.py", line 11, in <module>
    from keras.src.utils.module_utils import tensorflow as tf
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/utils/__init__.py", line 1, in <module>
    from keras.src.utils.audio_dataset_utils import audio_dataset_from_directory
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/utils/audio_dataset_utils.py", line 4, in <module>
    from keras.src.utils import dataset_utils
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/utils/dataset_utils.py", line 9, in <module>
    from keras.src import tree
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/tree/__init__.py", line 1, in <module>
    from keras.src.tree.tree_api import assert_same_structure
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/tree/tree_api.py", line 6, in <module>
    from keras.src.tree import optree_impl as tree_impl
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/tree/optree_impl.py", line 17, in <module>
    from tensorflow.python.trackable.data_structures import ListWrapper
ModuleNotFoundError: No module named 'tensorflow'
[2024-10-09T02:07:07.841+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:07:07.854+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 1.143 seconds
[2024-10-09T02:07:38.665+0000] {processor.py:161} INFO - Started process (PID=276) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:07:38.666+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T02:07:38.668+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:07:38.667+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:07:39.689+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:07:39.686+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 14, in <module>
    from keras.models import Sequential
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/__init__.py", line 4, in <module>
    from keras.api import DTypePolicy
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/api/__init__.py", line 8, in <module>
    from keras.api import activations
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/api/activations/__init__.py", line 7, in <module>
    from keras.src.activations import deserialize
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/__init__.py", line 1, in <module>
    from keras.src import activations
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/activations/__init__.py", line 3, in <module>
    from keras.src.activations.activations import elu
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/activations/activations.py", line 1, in <module>
    from keras.src import backend
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/backend/__init__.py", line 9, in <module>
    from keras.src.backend.common.dtypes import result_type
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/backend/common/__init__.py", line 2, in <module>
    from keras.src.backend.common.dtypes import result_type
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/backend/common/dtypes.py", line 5, in <module>
    from keras.src.backend.common.variables import standardize_dtype
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/backend/common/variables.py", line 11, in <module>
    from keras.src.utils.module_utils import tensorflow as tf
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/utils/__init__.py", line 1, in <module>
    from keras.src.utils.audio_dataset_utils import audio_dataset_from_directory
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/utils/audio_dataset_utils.py", line 4, in <module>
    from keras.src.utils import dataset_utils
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/utils/dataset_utils.py", line 9, in <module>
    from keras.src import tree
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/tree/__init__.py", line 1, in <module>
    from keras.src.tree.tree_api import assert_same_structure
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/tree/tree_api.py", line 6, in <module>
    from keras.src.tree import optree_impl as tree_impl
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/tree/optree_impl.py", line 17, in <module>
    from tensorflow.python.trackable.data_structures import ListWrapper
ModuleNotFoundError: No module named 'tensorflow'
[2024-10-09T02:07:39.691+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:07:39.702+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 1.043 seconds
[2024-10-09T02:08:10.226+0000] {processor.py:161} INFO - Started process (PID=344) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:08:10.230+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T02:08:10.233+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:08:10.233+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:08:11.252+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:08:11.249+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 14, in <module>
    from keras.models import Sequential
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/__init__.py", line 4, in <module>
    from keras.api import DTypePolicy
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/api/__init__.py", line 8, in <module>
    from keras.api import activations
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/api/activations/__init__.py", line 7, in <module>
    from keras.src.activations import deserialize
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/__init__.py", line 1, in <module>
    from keras.src import activations
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/activations/__init__.py", line 3, in <module>
    from keras.src.activations.activations import elu
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/activations/activations.py", line 1, in <module>
    from keras.src import backend
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/backend/__init__.py", line 9, in <module>
    from keras.src.backend.common.dtypes import result_type
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/backend/common/__init__.py", line 2, in <module>
    from keras.src.backend.common.dtypes import result_type
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/backend/common/dtypes.py", line 5, in <module>
    from keras.src.backend.common.variables import standardize_dtype
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/backend/common/variables.py", line 11, in <module>
    from keras.src.utils.module_utils import tensorflow as tf
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/utils/__init__.py", line 1, in <module>
    from keras.src.utils.audio_dataset_utils import audio_dataset_from_directory
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/utils/audio_dataset_utils.py", line 4, in <module>
    from keras.src.utils import dataset_utils
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/utils/dataset_utils.py", line 9, in <module>
    from keras.src import tree
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/tree/__init__.py", line 1, in <module>
    from keras.src.tree.tree_api import assert_same_structure
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/tree/tree_api.py", line 6, in <module>
    from keras.src.tree import optree_impl as tree_impl
  File "/home/airflow/.local/lib/python3.12/site-packages/keras/src/tree/optree_impl.py", line 17, in <module>
    from tensorflow.python.trackable.data_structures import ListWrapper
ModuleNotFoundError: No module named 'tensorflow'
[2024-10-09T02:08:11.253+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:08:11.265+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 1.049 seconds
[2024-10-09T02:11:13.840+0000] {processor.py:161} INFO - Started process (PID=83) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:11:13.842+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T02:11:13.845+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:11:13.844+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:11:16.354+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:11:16.354+0000] {font_manager.py:1584} INFO - generated new fontManager
[2024-10-09T02:11:21.490+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:11:21.485+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 23, in <module>
    @dag(dag_id='train_ml_model_dag',
     ^^^
NameError: name 'dag' is not defined
[2024-10-09T02:11:21.492+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:11:21.512+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 7.680 seconds
[2024-10-09T02:11:51.849+0000] {processor.py:161} INFO - Started process (PID=179) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:11:51.852+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T02:11:51.855+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:11:51.854+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:11:55.223+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:11:55.219+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 23, in <module>
    @dag(dag_id='train_ml_model_dag',
     ^^^
NameError: name 'dag' is not defined
[2024-10-09T02:11:55.224+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:11:55.241+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 3.402 seconds
[2024-10-09T02:12:25.688+0000] {processor.py:161} INFO - Started process (PID=263) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:12:25.690+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T02:12:25.694+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:12:25.693+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:12:29.083+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:12:29.077+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 23, in <module>
    @dag(dag_id='train_ml_model_dag',
     ^^^
NameError: name 'dag' is not defined
[2024-10-09T02:12:29.085+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:12:29.108+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 3.429 seconds
[2024-10-09T02:12:59.515+0000] {processor.py:161} INFO - Started process (PID=329) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:12:59.518+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T02:12:59.521+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:12:59.520+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:13:02.009+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:13:01.987+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 23, in <module>
    @dag(dag_id='train_ml_model_dag',
     ^^^
NameError: name 'dag' is not defined
[2024-10-09T02:13:02.015+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:13:02.047+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 2.543 seconds
[2024-10-09T02:13:32.319+0000] {processor.py:161} INFO - Started process (PID=393) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:13:32.323+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T02:13:32.327+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:13:32.326+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:13:34.883+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:13:34.878+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 23, in <module>
    default_args = default_args,
    ^^^
NameError: name 'dag' is not defined
[2024-10-09T02:13:34.885+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:13:34.903+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 2.594 seconds
[2024-10-09T02:17:04.099+0000] {processor.py:161} INFO - Started process (PID=91) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:17:04.101+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T02:17:04.103+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:17:04.103+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:17:05.881+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:17:05.880+0000] {font_manager.py:1584} INFO - generated new fontManager
[2024-10-09T02:17:08.531+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:17:08.527+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 22, in <module>
    @dag(dag_id='train_ml_model_dag',
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: dag() got an unexpected keyword argument 'cathup'
[2024-10-09T02:17:08.533+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:17:08.567+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 4.473 seconds
[2024-10-09T02:17:38.957+0000] {processor.py:161} INFO - Started process (PID=182) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:17:38.959+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T02:17:38.963+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:17:38.962+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:17:42.884+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:17:42.877+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 22, in <module>
    @dag(dag_id='train_ml_model_dag',
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: dag() got an unexpected keyword argument 'cathup'
[2024-10-09T02:17:42.885+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:17:42.906+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 3.958 seconds
[2024-10-09T02:18:13.224+0000] {processor.py:161} INFO - Started process (PID=273) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:18:13.225+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T02:18:13.227+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:18:13.227+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:18:15.604+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:18:15.600+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/train_ml_model.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/train_ml_model.py", line 22, in <module>
    @dag(dag_id='train_ml_model_dag',
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: dag() got an unexpected keyword argument 'cathup'
[2024-10-09T02:18:15.605+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:18:15.626+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 2.406 seconds
[2024-10-09T02:18:23.821+0000] {processor.py:161} INFO - Started process (PID=279) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:18:23.823+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T02:18:23.829+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:18:23.828+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:18:26.554+0000] {processor.py:840} INFO - DAG(s) 'train_ml_model_dag' retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:18:26.665+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:18:26.663+0000] {override.py:1829} INFO - Created Permission View: can read on DAG:train_ml_model_dag
[2024-10-09T02:18:26.675+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:18:26.675+0000] {override.py:1829} INFO - Created Permission View: can delete on DAG:train_ml_model_dag
[2024-10-09T02:18:26.678+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:18:26.678+0000] {override.py:1829} INFO - Created Permission View: can edit on DAG:train_ml_model_dag
[2024-10-09T02:18:26.679+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:18:26.679+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-09T02:18:26.687+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:18:26.687+0000] {dag.py:3118} INFO - Creating ORM DAG for train_ml_model_dag
[2024-10-09T02:18:26.688+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:18:26.688+0000] {dag.py:3954} INFO - Setting next_dagrun for train_ml_model_dag to None, run_after=None
[2024-10-09T02:18:26.699+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 2.888 seconds
[2024-10-09T02:21:35.248+0000] {processor.py:161} INFO - Started process (PID=91) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:21:35.249+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T02:21:35.251+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:21:35.251+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:21:38.566+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:21:38.564+0000] {font_manager.py:1584} INFO - generated new fontManager
[2024-10-09T02:21:45.318+0000] {processor.py:840} INFO - DAG(s) 'train_ml_model_dag' retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:21:45.486+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:21:45.483+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-09T02:21:45.522+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:21:45.522+0000] {dag.py:3954} INFO - Setting next_dagrun for train_ml_model_dag to None, run_after=None
[2024-10-09T02:21:45.564+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 10.324 seconds
[2024-10-09T02:22:16.510+0000] {processor.py:161} INFO - Started process (PID=191) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:22:16.512+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T02:22:16.515+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:22:16.514+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:22:23.844+0000] {processor.py:840} INFO - DAG(s) 'train_ml_model_dag' retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:22:23.905+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:22:23.903+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-09T02:22:23.917+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:22:23.917+0000] {dag.py:3954} INFO - Setting next_dagrun for train_ml_model_dag to None, run_after=None
[2024-10-09T02:22:23.930+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 7.398 seconds
[2024-10-09T02:22:54.447+0000] {processor.py:161} INFO - Started process (PID=272) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:22:54.450+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T02:22:54.455+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:22:54.454+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:22:58.244+0000] {processor.py:840} INFO - DAG(s) 'train_ml_model_dag' retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:22:58.293+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:22:58.292+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-09T02:22:58.299+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:22:58.299+0000] {dag.py:3954} INFO - Setting next_dagrun for train_ml_model_dag to None, run_after=None
[2024-10-09T02:22:58.313+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 3.896 seconds
[2024-10-09T02:23:28.594+0000] {processor.py:161} INFO - Started process (PID=336) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:23:28.597+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T02:23:28.600+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:23:28.599+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:23:32.161+0000] {processor.py:840} INFO - DAG(s) 'train_ml_model_dag' retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:23:32.202+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:23:32.200+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-09T02:23:32.208+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:23:32.208+0000] {dag.py:3954} INFO - Setting next_dagrun for train_ml_model_dag to None, run_after=None
[2024-10-09T02:23:32.217+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 3.633 seconds
[2024-10-09T02:24:02.738+0000] {processor.py:161} INFO - Started process (PID=407) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:24:02.748+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T02:24:02.763+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:24:02.761+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:24:06.541+0000] {processor.py:840} INFO - DAG(s) 'train_ml_model_dag' retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:24:06.586+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:24:06.585+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-09T02:24:06.594+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:24:06.594+0000] {dag.py:3954} INFO - Setting next_dagrun for train_ml_model_dag to None, run_after=None
[2024-10-09T02:24:06.605+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 3.880 seconds
[2024-10-09T02:24:37.641+0000] {processor.py:161} INFO - Started process (PID=472) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:24:37.643+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T02:24:37.647+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:24:37.646+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:24:42.065+0000] {processor.py:840} INFO - DAG(s) 'train_ml_model_dag' retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:24:42.081+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:24:42.080+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-09T02:24:42.089+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:24:42.088+0000] {dag.py:3954} INFO - Setting next_dagrun for train_ml_model_dag to None, run_after=None
[2024-10-09T02:24:42.099+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 4.490 seconds
[2024-10-09T02:25:12.695+0000] {processor.py:161} INFO - Started process (PID=548) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:25:12.697+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T02:25:12.699+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:25:12.699+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:25:16.551+0000] {processor.py:840} INFO - DAG(s) 'train_ml_model_dag' retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:25:16.569+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:25:16.569+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-09T02:25:16.576+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:25:16.576+0000] {dag.py:3954} INFO - Setting next_dagrun for train_ml_model_dag to None, run_after=None
[2024-10-09T02:25:16.585+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 3.898 seconds
[2024-10-09T02:25:46.718+0000] {processor.py:161} INFO - Started process (PID=623) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:25:46.720+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T02:25:46.723+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:25:46.722+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:25:51.132+0000] {processor.py:840} INFO - DAG(s) 'train_ml_model_dag' retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:25:51.155+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:25:51.155+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-09T02:25:51.162+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:25:51.162+0000] {dag.py:3954} INFO - Setting next_dagrun for train_ml_model_dag to None, run_after=None
[2024-10-09T02:25:51.175+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 4.466 seconds
[2024-10-09T02:26:21.681+0000] {processor.py:161} INFO - Started process (PID=699) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:26:21.682+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T02:26:21.687+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:26:21.686+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:26:25.700+0000] {processor.py:840} INFO - DAG(s) 'train_ml_model_dag' retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:26:25.748+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:26:25.746+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-09T02:26:25.762+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:26:25.762+0000] {dag.py:3954} INFO - Setting next_dagrun for train_ml_model_dag to None, run_after=None
[2024-10-09T02:26:25.774+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 4.104 seconds
[2024-10-09T02:26:56.722+0000] {processor.py:161} INFO - Started process (PID=778) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:26:56.724+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T02:26:56.727+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:26:56.726+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:27:00.161+0000] {processor.py:840} INFO - DAG(s) 'train_ml_model_dag' retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:27:00.200+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:27:00.200+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-09T02:27:00.207+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:27:00.207+0000] {dag.py:3954} INFO - Setting next_dagrun for train_ml_model_dag to None, run_after=None
[2024-10-09T02:27:00.215+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 3.502 seconds
[2024-10-09T02:27:30.831+0000] {processor.py:161} INFO - Started process (PID=842) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:27:30.834+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T02:27:30.838+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:27:30.837+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:27:35.163+0000] {processor.py:840} INFO - DAG(s) 'train_ml_model_dag' retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:27:35.209+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:27:35.208+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-09T02:27:35.216+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:27:35.215+0000] {dag.py:3954} INFO - Setting next_dagrun for train_ml_model_dag to None, run_after=None
[2024-10-09T02:27:35.225+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 4.406 seconds
[2024-10-09T02:28:05.463+0000] {processor.py:161} INFO - Started process (PID=914) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:28:05.465+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T02:28:05.468+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:28:05.467+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:28:09.214+0000] {processor.py:840} INFO - DAG(s) 'train_ml_model_dag' retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:28:09.263+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:28:09.262+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-09T02:28:09.274+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:28:09.274+0000] {dag.py:3954} INFO - Setting next_dagrun for train_ml_model_dag to None, run_after=None
[2024-10-09T02:28:09.286+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 3.834 seconds
[2024-10-09T02:28:40.021+0000] {processor.py:161} INFO - Started process (PID=978) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:28:40.023+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T02:28:40.026+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:28:40.025+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:28:45.456+0000] {processor.py:840} INFO - DAG(s) 'train_ml_model_dag' retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:28:45.473+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:28:45.472+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-09T02:28:45.483+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:28:45.483+0000] {dag.py:3954} INFO - Setting next_dagrun for train_ml_model_dag to None, run_after=None
[2024-10-09T02:28:45.494+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 5.483 seconds
[2024-10-09T02:29:15.789+0000] {processor.py:161} INFO - Started process (PID=1055) to work on /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:29:15.791+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/train_ml_model.py for tasks to queue
[2024-10-09T02:29:15.793+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:29:15.792+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:29:20.853+0000] {processor.py:840} INFO - DAG(s) 'train_ml_model_dag' retrieved from /opt/airflow/dags/train_ml_model.py
[2024-10-09T02:29:20.898+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:29:20.896+0000] {dag.py:3096} INFO - Sync 1 DAGs
[2024-10-09T02:29:20.908+0000] {logging_mixin.py:188} INFO - [2024-10-09T02:29:20.908+0000] {dag.py:3954} INFO - Setting next_dagrun for train_ml_model_dag to None, run_after=None
[2024-10-09T02:29:20.925+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/train_ml_model.py took 5.141 seconds
